module DAQ_Data
{
   struct DaqData
   {
      long dID;  // data ID
      boolean BAT; // BATT
	  boolean GEN;
	  boolean ALT;
	  boolean INV;
	  boolean HORN;
	  boolean ProbeHeat;
	  boolean Servo;
	  boolean Missiles; // HYD1
	  boolean Rockets;
	  boolean Guns;
	  boolean Bombs;
	  boolean Auto;
	  boolean BLANK;
	  boolean GCSTransf;
	  boolean Avionics;
	  double Stick;
	  double Throttle;
	  boolean Pressurization;
	  boolean IFFOVR;
	  boolean CB24_MainLPCocx;
	  boolean CB24_HYD_Press;
	  boolean CB24_CDU;
	  boolean CB24_ASI;
	  boolean CB24_HDR;
	  boolean CB24_AC_Pitch;
	  boolean CB24_LP_Pump_Port;
	  boolean CB24_UC_Ctrl;
	  boolean CB24_MSTR_ARMT;
	  boolean CB24_GPS;
	  boolean CB24_WarningLights;
	  boolean CB24_ServoCtrl;
	  boolean CB24_LP_Pump_STBD;
	  boolean CB24_UC_Pos_Indicator;
	  boolean CB24_SI;
	  boolean CB24_Oxy1;
	  boolean CB24_Oxy2;
	  boolean CB24_EMG_HD_Pump;
	  boolean CB24_UHF;
	  boolean CB24_IFF;     
	  boolean CB24_AH;      //Artificial Horizon
	  boolean CB24_CAB_T;   //Cabin Temperature
	  boolean CB24_START;
	  boolean CB24_MBM;
	  boolean CDU_Page_L1;
	  boolean CDU_Page_L2;
	  boolean CDU_Page_L3;
	  boolean CDU_Page_L4;
	  boolean CDU_Page_L5;
	  boolean CDU_Page_R1;
	  boolean CDU_Page_R2;
	  boolean CDU_Page_R3;
	  boolean CDU_Page_R4;
	  boolean CDU_Page_R5;
	  boolean CDU_Left_TST;
	  boolean CDU_Left_PRV;
	  boolean CDU_Left_NXT;
	  boolean CDU_Left_BRT;
	  boolean CDU_Left_DIM;
	  boolean CDU_Numpad_N1;
	  boolean CDU_Numpad_N2;
	  boolean CDU_Numpad_N3;
	  boolean CDU_Numpad_N4;
	  boolean CDU_Numpad_N5;
	  boolean CDU_Numpad_N6;
	  boolean CDU_Numpad_N7;
	  boolean CDU_Numpad_N8;
	  boolean CDU_Numpad_N9;
	  boolean CDU_Numpad_N_Ent;
	  boolean CDU_Numpad_N0;
	  boolean CDU_Numpad_N_CLR;
	  boolean CDU_Right_ATK;
	  boolean CDU_Right_AA;
	  boolean CDU_Right_REC;
	  boolean CDU_Right_NAV;
	  boolean CDU_Right_DIV;
	  boolean CDU_Right_MEN;
	  boolean CDU_Right_OPS;
	  boolean CDU_Right_EMG;
	  boolean CDU_Right_GUID;
	  boolean CDU_Right_FUEL;
	  boolean CDU_Right_FIX;
	  boolean CDU_Right_N12;
	  boolean CDU_Right_ALT;
	  boolean CDU_Right_IFF;
	  boolean CDU_Right_DCL;
	  boolean CDU_Right_N16;
	  boolean UFP_Left_N1;
	  boolean UFP_Left_ACK;
	  boolean UFP_Left_MEN;
	  boolean UFP_Left_NT;
	  boolean UFP_Left_FW;
	  boolean UFP_Left_SGL;
	  boolean UFP_Left_NAV;
	  boolean UFP_Left_TH;
	  boolean UFP_Left_NXT;
	  boolean UFP_Left_N10;
	  boolean UFP_Left_CHR;
	  boolean UFP_Left_IFF;
	  boolean UFP_Numpad_N1;
	  boolean UFP_Numpad_N2;
	  boolean UFP_Numpad_N3;
	  boolean UFP_Numpad_N4;
	  boolean UFP_Numpad_N5;
	  boolean UFP_Numpad_N6;
	  boolean UFP_Numpad_N7;
	  boolean UFP_Numpad_N8;
	  boolean UFP_Numpad_N9;
	  boolean UFP_Numpad_N_Ent;
	  boolean UFP_Numpad_N0;
	  boolean UFP_Numpad_N_CLR;
	  boolean UFP_Right_DRF_CO;
	  boolean UFP_Right_VEL;
	  boolean UFP_Right_DCL;
	  boolean NAU;
	  boolean IFFON;
	  boolean OverSpeed;
	  boolean GauTst;
	  boolean IncidTst;
	  boolean CbyF;
	  boolean FuelDump;
      boolean UC_Down;
	  boolean TankJet;
	  boolean WinJet;
	  boolean FuselageJet;
	  boolean Prty;
      boolean REC;
      boolean UNK;
	  boolean ABrk_Override;
	  boolean MainLP;
	  boolean LPPump1;
	  boolean LPPump2;
	  boolean AB_Left;
	  boolean IGN_Ventil;
	  boolean StartIGN;
   };
   #pragma keylist DaqData dID
};
