// -*- C++ -*-
//
// $Id$

// ****  Code generated by the The ACE ORB (TAO) IDL Compiler ****
// TAO and the TAO IDL Compiler have been developed by:
//       Center for Distributed Object Computing
//       Washington University
//       St. Louis, MO
//       USA
//       http://www.cs.wustl.edu/~schmidt/doc-center.html
// and
//       Distributed Object Computing Laboratory
//       University of California at Irvine
//       Irvine, CA
//       USA
//       http://doc.ece.uci.edu/
// and
//       Institute for Software Integrated Systems
//       Vanderbilt University
//       Nashville, TN
//       USA
//       http://www.isis.vanderbilt.edu/
//
// Information about TAO is available at:
//     http://www.cs.wustl.edu/~schmidt/TAO.html

// TAO_IDL - Generated from
// be/be_codegen.cpp:135

#ifndef _TAO_IDL_DDS_DCPS_BUILTINTOPICSC_H_
#define _TAO_IDL_DDS_DCPS_BUILTINTOPICSC_H_


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include "tao/AnyTypeCode/AnyTypeCode_methods.h"
#include "tao/ORB.h"
#include "tao/Basic_Types.h"
#include "tao/String_Manager_T.h"
#include "tao/VarOut_T.h"
#include /**/ "tao/Versioned_Namespace.h"

#include "dds_builtinTopicsC.h"

#if defined (TAO_EXPORT_MACRO)
#undef TAO_EXPORT_MACRO
#endif
#define TAO_EXPORT_MACRO 

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:49

namespace DDS
{
  
  // TAO_IDL - Generated from
  // be/be_type.cpp:269
  
  struct Time_t;
  
  typedef
    TAO_Fixed_Var_T<
        Time_t
      >
    Time_t_var;
  
  typedef
    Time_t &
    Time_t_out;
  
  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:57
  
  struct  Time_t
  {
    typedef Time_t_var _var_type;
    typedef Time_t_out _out_type;
    
    static void _tao_any_destructor (void *);
    ::CORBA::Long sec;
    ::CORBA::ULong nanosec;
  };
  
  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:49
  
  extern  ::CORBA::TypeCode_ptr const _tc_Time_t;
  
  // TAO_IDL - Generated from
  // be/be_type.cpp:269
  
  struct EntityFactoryQosPolicy;
  
  typedef
    TAO_Fixed_Var_T<
        EntityFactoryQosPolicy
      >
    EntityFactoryQosPolicy_var;
  
  typedef
    EntityFactoryQosPolicy &
    EntityFactoryQosPolicy_out;
  
  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:57
  
  struct  EntityFactoryQosPolicy
  {
    typedef EntityFactoryQosPolicy_var _var_type;
    typedef EntityFactoryQosPolicy_out _out_type;
    
    static void _tao_any_destructor (void *);
    ::CORBA::Boolean autoenable_created_entities;
  };
  
  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:49
  
  extern  ::CORBA::TypeCode_ptr const _tc_EntityFactoryQosPolicy;
  
  // TAO_IDL - Generated from
  // be/be_type.cpp:269
  
  struct WriterDataLifecycleQosPolicy;
  
  typedef
    TAO_Fixed_Var_T<
        WriterDataLifecycleQosPolicy
      >
    WriterDataLifecycleQosPolicy_var;
  
  typedef
    WriterDataLifecycleQosPolicy &
    WriterDataLifecycleQosPolicy_out;
  
  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:57
  
  struct  WriterDataLifecycleQosPolicy
  {
    typedef WriterDataLifecycleQosPolicy_var _var_type;
    typedef WriterDataLifecycleQosPolicy_out _out_type;
    
    static void _tao_any_destructor (void *);
    ::CORBA::Boolean autodispose_unregistered_instances;
    DDS::Duration_t autopurge_suspended_samples_delay;
    DDS::Duration_t autounregister_instance_delay;
  };
  
  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:49
  
  extern  ::CORBA::TypeCode_ptr const _tc_WriterDataLifecycleQosPolicy;
  
  // TAO_IDL - Generated from
  // be/be_type.cpp:269
  
  struct ReaderDataLifecycleQosPolicy;
  
  typedef
    TAO_Fixed_Var_T<
        ReaderDataLifecycleQosPolicy
      >
    ReaderDataLifecycleQosPolicy_var;
  
  typedef
    ReaderDataLifecycleQosPolicy &
    ReaderDataLifecycleQosPolicy_out;
  
  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:57
  
  struct  ReaderDataLifecycleQosPolicy
  {
    typedef ReaderDataLifecycleQosPolicy_var _var_type;
    typedef ReaderDataLifecycleQosPolicy_out _out_type;
    
    static void _tao_any_destructor (void *);
    DDS::Duration_t autopurge_nowriter_samples_delay;
    DDS::Duration_t autopurge_disposed_samples_delay;
    ::CORBA::Boolean enable_invalid_samples;
  };
  
  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:49
  
  extern  ::CORBA::TypeCode_ptr const _tc_ReaderDataLifecycleQosPolicy;
  
  // TAO_IDL - Generated from
  // be/be_type.cpp:269
  
  struct SubscriptionKeyQosPolicy;
  
  typedef
    TAO_Var_Var_T<
        SubscriptionKeyQosPolicy
      >
    SubscriptionKeyQosPolicy_var;
  
  typedef
    TAO_Out_T<
        SubscriptionKeyQosPolicy
      >
    SubscriptionKeyQosPolicy_out;
  
  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:57
  
  struct  SubscriptionKeyQosPolicy
  {
    typedef SubscriptionKeyQosPolicy_var _var_type;
    typedef SubscriptionKeyQosPolicy_out _out_type;
    
    static void _tao_any_destructor (void *);
    ::CORBA::Boolean use_key_list;
    DDS::StringSeq key_list;
  };
  
  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:49
  
  extern  ::CORBA::TypeCode_ptr const _tc_SubscriptionKeyQosPolicy;
  
  // TAO_IDL - Generated from
  // be/be_type.cpp:269
  
  struct ReaderLifespanQosPolicy;
  
  typedef
    TAO_Fixed_Var_T<
        ReaderLifespanQosPolicy
      >
    ReaderLifespanQosPolicy_var;
  
  typedef
    ReaderLifespanQosPolicy &
    ReaderLifespanQosPolicy_out;
  
  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:57
  
  struct  ReaderLifespanQosPolicy
  {
    typedef ReaderLifespanQosPolicy_var _var_type;
    typedef ReaderLifespanQosPolicy_out _out_type;
    
    static void _tao_any_destructor (void *);
    ::CORBA::Boolean use_lifespan;
    DDS::Duration_t duration;
  };
  
  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:49
  
  extern  ::CORBA::TypeCode_ptr const _tc_ReaderLifespanQosPolicy;
  
  // TAO_IDL - Generated from
  // be/be_type.cpp:269
  
  struct ShareQosPolicy;
  
  typedef
    TAO_Var_Var_T<
        ShareQosPolicy
      >
    ShareQosPolicy_var;
  
  typedef
    TAO_Out_T<
        ShareQosPolicy
      >
    ShareQosPolicy_out;
  
  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:57
  
  struct  ShareQosPolicy
  {
    typedef ShareQosPolicy_var _var_type;
    typedef ShareQosPolicy_out _out_type;
    
    static void _tao_any_destructor (void *);
    TAO::String_Manager name;
    ::CORBA::Boolean enable;
  };
  
  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:49
  
  extern  ::CORBA::TypeCode_ptr const _tc_ShareQosPolicy;
  
  // TAO_IDL - Generated from
  // be/be_visitor_enum/enum_ch.cpp:57
  
  enum SchedulingClassQosPolicyKind
  {
    SCHEDULE_DEFAULT,
    SCHEDULE_TIMESHARING,
    SCHEDULE_REALTIME
  };
  
  typedef SchedulingClassQosPolicyKind &SchedulingClassQosPolicyKind_out;
  
  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:49
  
  extern  ::CORBA::TypeCode_ptr const _tc_SchedulingClassQosPolicyKind;
  
  // TAO_IDL - Generated from
  // be/be_type.cpp:269
  
  struct SchedulingClassQosPolicy;
  
  typedef
    TAO_Fixed_Var_T<
        SchedulingClassQosPolicy
      >
    SchedulingClassQosPolicy_var;
  
  typedef
    SchedulingClassQosPolicy &
    SchedulingClassQosPolicy_out;
  
  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:57
  
  struct  SchedulingClassQosPolicy
  {
    typedef SchedulingClassQosPolicy_var _var_type;
    typedef SchedulingClassQosPolicy_out _out_type;
    
    static void _tao_any_destructor (void *);
    DDS::SchedulingClassQosPolicyKind kind;
  };
  
  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:49
  
  extern  ::CORBA::TypeCode_ptr const _tc_SchedulingClassQosPolicy;
  
  // TAO_IDL - Generated from
  // be/be_visitor_enum/enum_ch.cpp:57
  
  enum SchedulingPriorityQosPolicyKind
  {
    PRIORITY_RELATIVE,
    PRIORITY_ABSOLUTE
  };
  
  typedef SchedulingPriorityQosPolicyKind &SchedulingPriorityQosPolicyKind_out;
  
  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:49
  
  extern  ::CORBA::TypeCode_ptr const _tc_SchedulingPriorityQosPolicyKind;
  
  // TAO_IDL - Generated from
  // be/be_type.cpp:269
  
  struct SchedulingPriorityQosPolicy;
  
  typedef
    TAO_Fixed_Var_T<
        SchedulingPriorityQosPolicy
      >
    SchedulingPriorityQosPolicy_var;
  
  typedef
    SchedulingPriorityQosPolicy &
    SchedulingPriorityQosPolicy_out;
  
  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:57
  
  struct  SchedulingPriorityQosPolicy
  {
    typedef SchedulingPriorityQosPolicy_var _var_type;
    typedef SchedulingPriorityQosPolicy_out _out_type;
    
    static void _tao_any_destructor (void *);
    DDS::SchedulingPriorityQosPolicyKind kind;
  };
  
  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:49
  
  extern  ::CORBA::TypeCode_ptr const _tc_SchedulingPriorityQosPolicy;
  
  // TAO_IDL - Generated from
  // be/be_type.cpp:269
  
  struct SchedulingQosPolicy;
  
  typedef
    TAO_Fixed_Var_T<
        SchedulingQosPolicy
      >
    SchedulingQosPolicy_var;
  
  typedef
    SchedulingQosPolicy &
    SchedulingQosPolicy_out;
  
  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:57
  
  struct  SchedulingQosPolicy
  {
    typedef SchedulingQosPolicy_var _var_type;
    typedef SchedulingQosPolicy_out _out_type;
    
    static void _tao_any_destructor (void *);
    DDS::SchedulingClassQosPolicy scheduling_class;
    DDS::SchedulingPriorityQosPolicy scheduling_priority_kind;
    ::CORBA::Long scheduling_priority;
  };
  
  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:49
  
  extern  ::CORBA::TypeCode_ptr const _tc_SchedulingQosPolicy;
  
  // TAO_IDL - Generated from
  // be/be_type.cpp:269
  
  struct ViewKeyQosPolicy;
  
  typedef
    TAO_Var_Var_T<
        ViewKeyQosPolicy
      >
    ViewKeyQosPolicy_var;
  
  typedef
    TAO_Out_T<
        ViewKeyQosPolicy
      >
    ViewKeyQosPolicy_out;
  
  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:57
  
  struct  ViewKeyQosPolicy
  {
    typedef ViewKeyQosPolicy_var _var_type;
    typedef ViewKeyQosPolicy_out _out_type;
    
    static void _tao_any_destructor (void *);
    ::CORBA::Boolean use_key_list;
    DDS::StringSeq key_list;
  };
  
  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:49
  
  extern  ::CORBA::TypeCode_ptr const _tc_ViewKeyQosPolicy;
  
  // TAO_IDL - Generated from
  // be/be_type.cpp:269
  
  struct DataReaderViewQos;
  
  typedef
    TAO_Var_Var_T<
        DataReaderViewQos
      >
    DataReaderViewQos_var;
  
  typedef
    TAO_Out_T<
        DataReaderViewQos
      >
    DataReaderViewQos_out;
  
  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:57
  
  struct  DataReaderViewQos
  {
    typedef DataReaderViewQos_var _var_type;
    typedef DataReaderViewQos_out _out_type;
    
    static void _tao_any_destructor (void *);
    DDS::ViewKeyQosPolicy view_keys;
  };
  
  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:49
  
  extern  ::CORBA::TypeCode_ptr const _tc_DataReaderViewQos;
  
  // TAO_IDL - Generated from
  // be/be_type.cpp:269
  
  struct DomainParticipantFactoryQos;
  
  typedef
    TAO_Fixed_Var_T<
        DomainParticipantFactoryQos
      >
    DomainParticipantFactoryQos_var;
  
  typedef
    DomainParticipantFactoryQos &
    DomainParticipantFactoryQos_out;
  
  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:57
  
  struct  DomainParticipantFactoryQos
  {
    typedef DomainParticipantFactoryQos_var _var_type;
    typedef DomainParticipantFactoryQos_out _out_type;
    
    static void _tao_any_destructor (void *);
    DDS::EntityFactoryQosPolicy entity_factory;
  };
  
  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:49
  
  extern  ::CORBA::TypeCode_ptr const _tc_DomainParticipantFactoryQos;
  
  // TAO_IDL - Generated from
  // be/be_type.cpp:269
  
  struct DomainParticipantQos;
  
  typedef
    TAO_Var_Var_T<
        DomainParticipantQos
      >
    DomainParticipantQos_var;
  
  typedef
    TAO_Out_T<
        DomainParticipantQos
      >
    DomainParticipantQos_out;
  
  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:57
  
  struct  DomainParticipantQos
  {
    typedef DomainParticipantQos_var _var_type;
    typedef DomainParticipantQos_out _out_type;
    
    static void _tao_any_destructor (void *);
    DDS::UserDataQosPolicy user_data;
    DDS::EntityFactoryQosPolicy entity_factory;
    DDS::SchedulingQosPolicy watchdog_scheduling;
    DDS::SchedulingQosPolicy listener_scheduling;
  };
  
  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:49
  
  extern  ::CORBA::TypeCode_ptr const _tc_DomainParticipantQos;
  
  // TAO_IDL - Generated from
  // be/be_type.cpp:269
  
  struct TopicQos;
  
  typedef
    TAO_Var_Var_T<
        TopicQos
      >
    TopicQos_var;
  
  typedef
    TAO_Out_T<
        TopicQos
      >
    TopicQos_out;
  
  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:57
  
  struct  TopicQos
  {
    typedef TopicQos_var _var_type;
    typedef TopicQos_out _out_type;
    
    static void _tao_any_destructor (void *);
    DDS::TopicDataQosPolicy topic_data;
    DDS::DurabilityQosPolicy durability;
    DDS::DurabilityServiceQosPolicy durability_service;
    DDS::DeadlineQosPolicy deadline;
    DDS::LatencyBudgetQosPolicy latency_budget;
    DDS::LivelinessQosPolicy liveliness;
    DDS::ReliabilityQosPolicy reliability;
    DDS::DestinationOrderQosPolicy destination_order;
    DDS::HistoryQosPolicy history;
    DDS::ResourceLimitsQosPolicy resource_limits;
    DDS::TransportPriorityQosPolicy transport_priority;
    DDS::LifespanQosPolicy lifespan;
    DDS::OwnershipQosPolicy ownership;
  };
  
  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:49
  
  extern  ::CORBA::TypeCode_ptr const _tc_TopicQos;
  
  // TAO_IDL - Generated from
  // be/be_type.cpp:269
  
  struct DataWriterQos;
  
  typedef
    TAO_Var_Var_T<
        DataWriterQos
      >
    DataWriterQos_var;
  
  typedef
    TAO_Out_T<
        DataWriterQos
      >
    DataWriterQos_out;
  
  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:57
  
  struct  DataWriterQos
  {
    typedef DataWriterQos_var _var_type;
    typedef DataWriterQos_out _out_type;
    
    static void _tao_any_destructor (void *);
    DDS::DurabilityQosPolicy durability;
    DDS::DeadlineQosPolicy deadline;
    DDS::LatencyBudgetQosPolicy latency_budget;
    DDS::LivelinessQosPolicy liveliness;
    DDS::ReliabilityQosPolicy reliability;
    DDS::DestinationOrderQosPolicy destination_order;
    DDS::HistoryQosPolicy history;
    DDS::ResourceLimitsQosPolicy resource_limits;
    DDS::TransportPriorityQosPolicy transport_priority;
    DDS::LifespanQosPolicy lifespan;
    DDS::UserDataQosPolicy user_data;
    DDS::OwnershipQosPolicy ownership;
    DDS::OwnershipStrengthQosPolicy ownership_strength;
    DDS::WriterDataLifecycleQosPolicy writer_data_lifecycle;
  };
  
  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:49
  
  extern  ::CORBA::TypeCode_ptr const _tc_DataWriterQos;
  
  // TAO_IDL - Generated from
  // be/be_type.cpp:269
  
  struct PublisherQos;
  
  typedef
    TAO_Var_Var_T<
        PublisherQos
      >
    PublisherQos_var;
  
  typedef
    TAO_Out_T<
        PublisherQos
      >
    PublisherQos_out;
  
  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:57
  
  struct  PublisherQos
  {
    typedef PublisherQos_var _var_type;
    typedef PublisherQos_out _out_type;
    
    static void _tao_any_destructor (void *);
    DDS::PresentationQosPolicy presentation;
    DDS::PartitionQosPolicy partition;
    DDS::GroupDataQosPolicy group_data;
    DDS::EntityFactoryQosPolicy entity_factory;
  };
  
  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:49
  
  extern  ::CORBA::TypeCode_ptr const _tc_PublisherQos;
  
  // TAO_IDL - Generated from
  // be/be_type.cpp:269
  
  struct DataReaderQos;
  
  typedef
    TAO_Var_Var_T<
        DataReaderQos
      >
    DataReaderQos_var;
  
  typedef
    TAO_Out_T<
        DataReaderQos
      >
    DataReaderQos_out;
  
  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:57
  
  struct  DataReaderQos
  {
    typedef DataReaderQos_var _var_type;
    typedef DataReaderQos_out _out_type;
    
    static void _tao_any_destructor (void *);
    DDS::DurabilityQosPolicy durability;
    DDS::DeadlineQosPolicy deadline;
    DDS::LatencyBudgetQosPolicy latency_budget;
    DDS::LivelinessQosPolicy liveliness;
    DDS::ReliabilityQosPolicy reliability;
    DDS::DestinationOrderQosPolicy destination_order;
    DDS::HistoryQosPolicy history;
    DDS::ResourceLimitsQosPolicy resource_limits;
    DDS::UserDataQosPolicy user_data;
    DDS::OwnershipQosPolicy ownership;
    DDS::TimeBasedFilterQosPolicy time_based_filter;
    DDS::ReaderDataLifecycleQosPolicy reader_data_lifecycle;
    DDS::SubscriptionKeyQosPolicy subscription_keys;
    DDS::ReaderLifespanQosPolicy reader_lifespan;
    DDS::ShareQosPolicy share;
  };
  
  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:49
  
  extern  ::CORBA::TypeCode_ptr const _tc_DataReaderQos;
  
  // TAO_IDL - Generated from
  // be/be_type.cpp:269
  
  struct SubscriberQos;
  
  typedef
    TAO_Var_Var_T<
        SubscriberQos
      >
    SubscriberQos_var;
  
  typedef
    TAO_Out_T<
        SubscriberQos
      >
    SubscriberQos_out;
  
  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:57
  
  struct  SubscriberQos
  {
    typedef SubscriberQos_var _var_type;
    typedef SubscriberQos_out _out_type;
    
    static void _tao_any_destructor (void *);
    DDS::PresentationQosPolicy presentation;
    DDS::PartitionQosPolicy partition;
    DDS::GroupDataQosPolicy group_data;
    DDS::EntityFactoryQosPolicy entity_factory;
    DDS::ShareQosPolicy share;
  };
  
  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:49
  
  extern  ::CORBA::TypeCode_ptr const _tc_SubscriberQos;

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:78

} // module DDS

// TAO_IDL - Generated from
// be/be_visitor_traits.cpp:64

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:53


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const DDS::Time_t &); // copying version
 void operator<<= (::CORBA::Any &, DDS::Time_t*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DDS::Time_t *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const DDS::Time_t *&);
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:53


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const DDS::EntityFactoryQosPolicy &); // copying version
 void operator<<= (::CORBA::Any &, DDS::EntityFactoryQosPolicy*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DDS::EntityFactoryQosPolicy *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const DDS::EntityFactoryQosPolicy *&);
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:53


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const DDS::WriterDataLifecycleQosPolicy &); // copying version
 void operator<<= (::CORBA::Any &, DDS::WriterDataLifecycleQosPolicy*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DDS::WriterDataLifecycleQosPolicy *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const DDS::WriterDataLifecycleQosPolicy *&);
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:53


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const DDS::ReaderDataLifecycleQosPolicy &); // copying version
 void operator<<= (::CORBA::Any &, DDS::ReaderDataLifecycleQosPolicy*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DDS::ReaderDataLifecycleQosPolicy *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const DDS::ReaderDataLifecycleQosPolicy *&);
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:53


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const DDS::SubscriptionKeyQosPolicy &); // copying version
 void operator<<= (::CORBA::Any &, DDS::SubscriptionKeyQosPolicy*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DDS::SubscriptionKeyQosPolicy *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const DDS::SubscriptionKeyQosPolicy *&);
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:53


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const DDS::ReaderLifespanQosPolicy &); // copying version
 void operator<<= (::CORBA::Any &, DDS::ReaderLifespanQosPolicy*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DDS::ReaderLifespanQosPolicy *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const DDS::ReaderLifespanQosPolicy *&);
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:53


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const DDS::ShareQosPolicy &); // copying version
 void operator<<= (::CORBA::Any &, DDS::ShareQosPolicy*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DDS::ShareQosPolicy *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const DDS::ShareQosPolicy *&);
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_enum/any_op_ch.cpp:52
TAO_BEGIN_VERSIONED_NAMESPACE_DECL



 void operator<<= (::CORBA::Any &, DDS::SchedulingClassQosPolicyKind);
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DDS::SchedulingClassQosPolicyKind &);
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:53


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const DDS::SchedulingClassQosPolicy &); // copying version
 void operator<<= (::CORBA::Any &, DDS::SchedulingClassQosPolicy*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DDS::SchedulingClassQosPolicy *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const DDS::SchedulingClassQosPolicy *&);
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_enum/any_op_ch.cpp:52
TAO_BEGIN_VERSIONED_NAMESPACE_DECL



 void operator<<= (::CORBA::Any &, DDS::SchedulingPriorityQosPolicyKind);
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DDS::SchedulingPriorityQosPolicyKind &);
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:53


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const DDS::SchedulingPriorityQosPolicy &); // copying version
 void operator<<= (::CORBA::Any &, DDS::SchedulingPriorityQosPolicy*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DDS::SchedulingPriorityQosPolicy *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const DDS::SchedulingPriorityQosPolicy *&);
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:53


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const DDS::SchedulingQosPolicy &); // copying version
 void operator<<= (::CORBA::Any &, DDS::SchedulingQosPolicy*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DDS::SchedulingQosPolicy *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const DDS::SchedulingQosPolicy *&);
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:53


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const DDS::ViewKeyQosPolicy &); // copying version
 void operator<<= (::CORBA::Any &, DDS::ViewKeyQosPolicy*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DDS::ViewKeyQosPolicy *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const DDS::ViewKeyQosPolicy *&);
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:53


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const DDS::DataReaderViewQos &); // copying version
 void operator<<= (::CORBA::Any &, DDS::DataReaderViewQos*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DDS::DataReaderViewQos *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const DDS::DataReaderViewQos *&);
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:53


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const DDS::DomainParticipantFactoryQos &); // copying version
 void operator<<= (::CORBA::Any &, DDS::DomainParticipantFactoryQos*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DDS::DomainParticipantFactoryQos *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const DDS::DomainParticipantFactoryQos *&);
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:53


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const DDS::DomainParticipantQos &); // copying version
 void operator<<= (::CORBA::Any &, DDS::DomainParticipantQos*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DDS::DomainParticipantQos *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const DDS::DomainParticipantQos *&);
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:53


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const DDS::TopicQos &); // copying version
 void operator<<= (::CORBA::Any &, DDS::TopicQos*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DDS::TopicQos *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const DDS::TopicQos *&);
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:53


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const DDS::DataWriterQos &); // copying version
 void operator<<= (::CORBA::Any &, DDS::DataWriterQos*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DDS::DataWriterQos *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const DDS::DataWriterQos *&);
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:53


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const DDS::PublisherQos &); // copying version
 void operator<<= (::CORBA::Any &, DDS::PublisherQos*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DDS::PublisherQos *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const DDS::PublisherQos *&);
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:53


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const DDS::DataReaderQos &); // copying version
 void operator<<= (::CORBA::Any &, DDS::DataReaderQos*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DDS::DataReaderQos *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const DDS::DataReaderQos *&);
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:53


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const DDS::SubscriberQos &); // copying version
 void operator<<= (::CORBA::Any &, DDS::SubscriberQos*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DDS::SubscriberQos *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const DDS::SubscriberQos *&);
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:54


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const DDS::Time_t &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, DDS::Time_t &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:54


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const DDS::EntityFactoryQosPolicy &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, DDS::EntityFactoryQosPolicy &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:54


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const DDS::WriterDataLifecycleQosPolicy &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, DDS::WriterDataLifecycleQosPolicy &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:54


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const DDS::ReaderDataLifecycleQosPolicy &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, DDS::ReaderDataLifecycleQosPolicy &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:54


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const DDS::SubscriptionKeyQosPolicy &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, DDS::SubscriptionKeyQosPolicy &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:54


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const DDS::ReaderLifespanQosPolicy &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, DDS::ReaderLifespanQosPolicy &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:54


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const DDS::ShareQosPolicy &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, DDS::ShareQosPolicy &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_enum/cdr_op_ch.cpp:50


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &strm, DDS::SchedulingClassQosPolicyKind _tao_enumerator);
 ::CORBA::Boolean operator>> (TAO_InputCDR &strm, DDS::SchedulingClassQosPolicyKind &_tao_enumerator);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:54


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const DDS::SchedulingClassQosPolicy &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, DDS::SchedulingClassQosPolicy &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_enum/cdr_op_ch.cpp:50


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &strm, DDS::SchedulingPriorityQosPolicyKind _tao_enumerator);
 ::CORBA::Boolean operator>> (TAO_InputCDR &strm, DDS::SchedulingPriorityQosPolicyKind &_tao_enumerator);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:54


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const DDS::SchedulingPriorityQosPolicy &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, DDS::SchedulingPriorityQosPolicy &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:54


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const DDS::SchedulingQosPolicy &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, DDS::SchedulingQosPolicy &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:54


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const DDS::ViewKeyQosPolicy &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, DDS::ViewKeyQosPolicy &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:54


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const DDS::DataReaderViewQos &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, DDS::DataReaderViewQos &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:54


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const DDS::DomainParticipantFactoryQos &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, DDS::DomainParticipantFactoryQos &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:54


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const DDS::DomainParticipantQos &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, DDS::DomainParticipantQos &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:54


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const DDS::TopicQos &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, DDS::TopicQos &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:54


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const DDS::DataWriterQos &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, DDS::DataWriterQos &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:54


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const DDS::PublisherQos &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, DDS::PublisherQos &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:54


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const DDS::DataReaderQos &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, DDS::DataReaderQos &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:54


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const DDS::SubscriberQos &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, DDS::SubscriberQos &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_codegen.cpp:1226
#if defined (__ACE_INLINE__)
#include "dds_dcps_builtintopicsC.i"
#endif /* defined INLINE */

#endif /* ifndef */


