module JSBSim
{
   struct position
   {
      	long    ID;    // User ID
      	double epa_rad                   ;   
      	double h_sl_ft                   ;
	double h_sl_meters               ;
	double lat_gc_rad                ;
	double long_gc_rad               ;
	double lat_gc_deg                ;
	double long_gc_deg               ;
	double lat_geod_rad              ;
	double lat_geod_deg              ;
	double geod_alt_ft               ;
	double h_agl_ft                  ;
	double radius_to_vehicle_ft      ;
	double terrain_elevation_asl_ft  ;
	double distance_from_start_lon_mt;
	double distance_from_start_lat_mt;
	double distance_from_start_mag_mt;

	double pdot_rad_sec2    ;        
	double qdot_rad_sec2    ;
    	double rdot_rad_sec2    ;
    	double udot_ft_sec2     ;
    	double vdot_ft_sec2     ;
    	double wdot_ft_sec2     ;
    	double a_pilot_x_ft_sec2;
    	double a_pilot_y_ft_sec2;
    	double a_pilot_z_ft_sec2;
    	double n_pilot_x_norm   ;
    	double n_pilot_y_norm   ;
    	double n_pilot_z_norm   ;   
    	double Nz; 

	double phi_rad         ;
    	double theta_rad       ;
   	double psi_rad         ;
   	double roll_rad        ;
    	double pitch_rad       ;
    	double heading_true_rad; 
   
      	double integrator_rate_rotational       ; 
      	double integrator_rate_translational    ;
    	double integrator_position_rotational   ;
    	double integrator_position_translational;
    	double write_state_file                 ;
    	double do_simple_trim                   ;
    	double reset                            ;
    	double terminate                        ;
    	double frame_start_time                 ;
   	double cycle_duration                   ;  
	    	double flight_path_gamma_rad;
	   	double flight_path_psi_gt_rad;

	        double h_dot_fps	;	
	    	double v_north_fps           ;
	    	double v_east_fps            ;
	    	double v_down_fps            ;
		double u_fps                 ;
		double v_fps                 ;
		double w_fps                 ;
		double p_rad_sec             ;
		double q_rad_sec             ;
		double r_rad_sec             ;
		double pi_rad_sec            ;
		double qi_rad_sec            ;
		double ri_rad_sec            ;
		double eci_velocity_mag_fps  ;
		double vc_fps                ;
		double vc_kts                ;
		double ve_fps                ;
		double ve_kts                ;
		double machU                 ;
		double p_aero_rad_sec        ;
		double q_aero_rad_sec        ;
		double r_aero_rad_sec        ;
		double phidot_rad_sec        ;
		double thetadot_rad_sec      ;
		double psidot_rad_sec        ;
		double u_aero_fps            ;
		double v_aero_fps            ;
		double w_aero_fps            ;
		double vt_fps                ;
		double mach                  ;
		double vg_fps                ;

 		double T_R;
		double rho_slugs_ft3;
		double P_psf;
		double a_fps;
		double T_sl_R;
		double rho_sl_slugs_ft3;
		double P_sl_psf;
		double a_sl_fps;
		double theta;
		double sigma;
		double delta;
		double a_ratio;
		double psiw_rad;
		double delta_T;
		double T_sl_dev_F;
		double density_altitude;
		double wind_north_fps;
		double wind_east_fps;
		double wind_down_fps;
		double wind_mag_fps;
		double total_wind_north_fps;
		double total_wind_east_fps;
		double total_wind_down_fps;
		double gust_north_fps;
		double gust_east_fps;
		double gust_down_fps;
		double p_turb_rad_sec;
		double q_turb_rad_sec;
		double r_turb_rad_sec;
		double turb_rate;
		double turb_gain;
		double turb_rhythmicity;

          double aileron_cmd_norm;
		double elevator_cmd_norm;
		double rudder_cmd_norm;
		double flap_cmd_norm;
		double speedbrake_cmd_norm;
		double spoiler_cmd_norm;
		double pitch_trim_cmd_norm;
		double roll_trim_cmd_norm;
		double yaw_trim_cmd_norm;
		double left_aileron_pos_rad;
		double left_aileron_pos_deg;
		double left_aileron_pos_norm;
		double mag_left_aileron_pos_rad;
		double right_aileron_pos_rad;
		double right_aileron_pos_deg;
		double right_aileron_pos_norm;
		double mag_right_aileron_pos_rad;
		double elevator_pos_rad;
		double elevator_pos_deg;
		double elevator_pos_norm;
		double mag_elevator_pos_rad;
		double rudder_pos_rad;
		double rudder_pos_deg;
		double rudder_pos_norm;
		double mag_rudder_pos_rad;
		double flap_pos_rad;
		double flap_pos_deg;
		double flap_pos_norm;
		double speedbrake_pos_rad;
		double speedbrake_pos_deg;
		double speedbrake_pos_norm;
		double mag_speedbrake_pos_rad;
		double spoiler_pos_rad;
		double spoiler_pos_deg;
		double spoiler_pos_norm;
		double mag_spoiler_pos_rad;
		double left_brake_cmd_norm;
		double right_brake_cmd_norm;
		double center_brake_cmd_norm;
		double steer_cmd_norm;
		double wing_fold_pos_norm;
		double throttle_cmd_norm;
		double throttle_pos_norm;
		double mixture_cmd_norm;
		double mixture_pos_norm;
		double advance_cmd_norm;
		double advance_pos_norm;
		double feather_cmd_norm;
		double feather_pos_norm;
		double steer_pos_deg;
		double alpha_norm;
		double elevator_cmd_limiter;
		double g_load_norm;
		double alpha_limiter;
		double g_load_error;
		double g_load_p;
		double g_load_i;
		double g_load_d;
		double g_load_command;
		double elevator_control;
		double roll_rate_norm;
		double roll_trim_error;
		double roll_rate_p;
		double roll_rate_i;
		double roll_rate_d;
		double roll_rate_command;
		double left_aileron_control;
		double right_aileron_control;
		double yaw_rate_norm;
		double yaw_trim_error;
		double yaw_rate_p;
		double yaw_rate_i;
		double yaw_rate_d;
		double yaw_command;
		double rudder_control;
		double alpha_norm_gain;
		double lef_pos_deg;
		double lef_pos_norm;
		double throttle1;
		double flap_command;
		double flaps_control;
		double flap_position_normalizer;
		double speedbrake_control;
		double gear_control;
		double scheduled_steer_pos_deg;
	
           
		double gear_pos_norm              ;
		double gear_cmd_norm              ;
		double tailhook_pos_norm          ;
		double num_units                  ;
		double slip_angle_deg[3]        ;
		double WOW[3]                   ;
		double wheel_speed_fps[3]       ;
		double z_position[3]            ;
		double compression_ft[3]        ;
		double side_friction_coeff[3]   ;
		double pos_norm[3]              ;

                
                double mass_slugs                 ;        
		double weight_lbs                 ;
		double empty_weight_lbs           ;
		double cg_x_in                    ;
		double cg_y_in                    ;
		double cg_z_in                    ;
		double pointmass_weight_lbs       ;
		double pointmass_location_X_inches;
		double pointmass_location_Y_inches;
		double pointmass_location_Z_inches;
		double bx_aero_lbs                ;
		double by_aero_lbs                ;
		double bz_aero_lbs                ;
		double wx_aero_lbs                ;
		double wy_aero_lbs                ;
		double wz_aero_lbs                ;
		double od_norm                    ;
		double bx_gear_lbs                ;
		double by_gear_lbs                ;
		double bz_gear_lbs                ;
		double bx_total_lbs               ;
		double by_total_lbs               ;
		double bz_total_lbs               ;
		double oad_factor                 ;
		double old_down                   ;
		double bx_prop_lbs                ;
		double by_prop_lbs                ;
		double bz_prop_lbs                ;
		double l_aero_lbsft               ;
		double m_aero_lbsft               ;
		double n_aero_lbsft               ;
		double l_gear_lbsft               ;
		double m_gear_lbsft               ;
		double n_gear_lbsft               ;
		double l_total_lbsft              ;
		double m_total_lbsft              ;
		double n_total_lbsft              ;
		double l_prop_lbsft               ;
		double m_prop_lbsft               ;
		double n_prop_lbsft               ;
     	
		double cl_squared          ;   
		double qbar_area           ;
		double alpha_max_rad       ;
		double alpha_min_rad       ;
		double bi2vel              ;
		double ci2vel              ;
		double alpha_wing_rad      ;
		double stall_hyst_norm     ;
		double alpha_rad           ;
		double beta_rad            ;
		double mag_beta_rad        ;
		double alpha_deg           ;
		double beta_deg            ;
		double mag_beta_deg        ;
		double Re                  ;
		double qbar_psf            ;
		double qbarUW_psf          ;
		double qbarUV_psf          ;
		double alphadot_rad_sec    ;
		double betadot_rad_sec     ;
		double alphadot_deg_sec    ;
		double betadot_deg_sec     ;
		double h_b_cg_ft           ;
		double h_b_mac_ft          ;
		double kCLge      ;         
		double stall_warn_norm;
  		
			
		double CDDh     ;
		double CDmach   ;
		double CDDlef   ;
		double CDDflaps ;
		double CDgear   ;
		double CDDsb    ;
		double CDq      ;
		double CDq_Dlef ;
		double CYb      ;
		double CYb_M    ;
		double CYDa     ;
		double CYdr     ;
		double CYp      ;
		double CYr      ;
		double CLDh     ;
		double CLDlef   ;
		double CLDflaps ;
		double CLDsb    ;
		double CLq      ;
		double CLq_Dsb  ;
		double Clb      ;
		double Clb_M    ;
		double Clp      ;
		double Clr      ;
		double Clda     ;
		double Clda_M   ;
		double Cldr_M   ;
		double Cldr     ;
		double CmDh     ;
		double Cma_M    ;
		double Cmq      ;
		double Cnb      ;
		double Cnb_M    ;
		double Cnp      ;
		double Cnr      ;
		double Cnda_M   ;
		double Cnda     ;
		double Cndr     ;
		double Cndr_M   ;

		double Sw_sqft;
		double bw_ft                 ;
		double cbarw_ft              ;
		double iw_rad                ;
		double iw_deg                ;
		double Sh_sqft               ;
		double lh_ft                 ;
		double Sv_sqft               ;
		double lv_ft                 ;
		double lh_norm               ;
		double lv_norm               ;
		double vbarh_norm            ;
		double vbarv_norm            ;
		double aero_rp_x_in          ;
		double aero_rp_y_in          ;
		double aero_rp_z_in          ;
		double eyepoint_x_in         ;
		double eyepoint_y_in         ;
		double eyepoint_z_in         ;
		double visualrefpoint_x_in   ;
		double visualrefpoint_y_in   ;
		double visualrefpoint_z_in   ;
		double terrain_radius        ;

		
		double tat_r                     ;
		double tat_c                     ;
		double pt_lbs_sqft               ;
		double set_running               ;
		double starter_cmd               ;
		double cutoff_cmd                ;
		double active_engine             ;
		double total_fuel_lbs            ;
		double refuel                    ;
		double fuel_dump                 ;
		double pitch_angle_rad           ;
		double yaw_angle_rad             ;
		double reverser_angle_rad        ;
		double thrust_lbs                ;
		double fuel_flow_rate_pps        ;
		double IdleThrust                ;
		double MilThrust                 ;
		double AugThrust                 ;
		double WindMilRPM                ;
		double n1                        ;
		double n2                        ;
		double injection_cmd             ;
		double phase                     ;
		double RPM                       ;
		double EmergencyThrottlePosition ;
		double EmergencyNozzleSwitch     ;
		double FuelDipperSwitch          ;
		double AugmentationSwitch        ;
		double EGT_degC                  ;
		double RelightSwitch             ;
		double AugmentationLight         ;
		double tank_contents_lbs[3]; 

		double roc_fpm                 ;
		double gamma_deg               ;
		double theta_deg               ;
		double phi_deg                 ;
		double psi_true_deg            ;
		double sea_level_radius_ft     ;
		double terrain_elevation_ft    ;
		double vw_bx_fps               ;
		double vw_by_fps               ;
		double vw_bz_fps               ;
		double vw_north_fps            ;
		double vw_east_fps             ;
		double vw_down_fps             ;
		double vw_mag_fps              ;
		double vw_dir_deg              ;
		double roc_fps                 ;
		double vn_fps                  ;
		double vd_fps                  ;
		double gamma_rad               ;
		double psi_true_rad            ;
		double CDdHT                   ;
	

		boolean electrical_GPU                        ;
		boolean electrical_BatteryBus                 ;
		boolean electrical_BatterySwitch              ;
		boolean electrical_ManualLoadShed             ;
		boolean electrical_GeneratorSwitch            ;
		boolean electrical_InverterSwitch             ;
		boolean electrical_AlternatorSwitch           ;
		double electrical_MainFailLightSwitch        ;
		boolean electrical_EmergencyParkingBrakeSwitch;
		double hydraulic_HydraulicPumpPressure       ;
		boolean hydraulic_ServoAccumulator            ;
		boolean hydraulic_EmergencyHydPumpSwitch      ;
		boolean hydraulic_EmergencyPump               ;
		double hydraulic_Hydraulic2PumpPressure      ;
		boolean hydraulic_PreservoHyd2                ;
		double hydraulic_HydraulicResservoir         ;
		boolean armament_MasterArmamentSwitch         ;
		boolean armament_NormalManual                 ;
		boolean armament_BombsSelection               ;
		boolean armament_GunsSelection                ;
		boolean armament_MissilesSelection            ;
		boolean armament_RocketsSelection             ;
		boolean armament_GunTrigger                   ;
		boolean armament_BRMTrigger                   ;
		boolean armament_FuelDipper                   ;
		boolean fuel_WingTankDropSwitch               ;
		boolean fuel_FuseLageTankDropSwitch           ;
		boolean fuel_ExTankDropSwitch                 ;
		boolean fuel_FuelDumpSwitch                   ;
		boolean fuel_MainLPPump                       ;
		boolean fuel_LPPumpRight                      ;
		boolean fuel_LPPumpLeft                       ;
		boolean fuel_CrossfeedCock                    ;
		boolean fuel_GaugeTest                        ;
		double  fuel_RPM                              ;
		double  fuel_FuelConsumptionRate              ;
	
		
		boolean output_BatteryBusOut                   ;
		boolean output_DC                              ;
		boolean output_Inverter                        ;
		boolean output_ALternator                      ;
		boolean output_AutoLoadSheddingAC              ;
		boolean output_AlternatorWarningLight          ;
		boolean output_GenernatorWarningLight          ;
		boolean output_BatteryWarningLight             ;
		double output_UnderCarriageExtension          ;
		double output_WheelBrake                      ;
		double output_SpeedBrake                      ;
		double output_ParkingBrake                    ;
		double output_OscarDashpot                    ;
		double output_LeftElevonControl               ;
		double output_RightElevonControl              ;
		double output_PreservoControl                 ;
		double output_PitchDamper                     ;
		boolean output_HydraulicIndicatorLight         ;
		boolean output_Hydraulic2IndicatorLight        ;
		boolean output_EmergencyHydraulicIndicator     ;
		double output_DualHydGuage1                   ;
		double output_DualHydGuage2                   ;
		double output_FuelTotalizer                   ;
		boolean output_LeftWingTankWarningLight        ;
		boolean output_CenterLineTankWarningLight      ;
		boolean output_InternalWingTankWarningLight    ;
		boolean output_UpperBayWarningLight            ;
		boolean output_RightWingTankWarningLight       ;
		boolean output_LitreWarningLight600            ;
		boolean output_LitreWarningLight400            ;
		double output_DFGLeft                         ;
		double output_DFGRight                        ;
		double output_MainFailLight                   ;
		double output_WarningHorn                     ;
		boolean output_BombIndication                  ;
		boolean output_GunIndication                   ;
		boolean output_MissileIndication               ;
		boolean output_RocketIndication                ;
		double output_RPMIncrease                     ;

		double FuelExpanded		;
		boolean AOAGreenFlag		;
		boolean AOAAmberFlag		;
		boolean AOARedFlag		;        
   };            
   #pragma keylist position ID
	struct DaqData
   	{
      		long ID;  // data ID
     		boolean BAT; // BATT
		boolean GEN;
		boolean ALT;
		boolean INV;
		boolean HORN;
		boolean ProbeHeat;
		boolean Servo;
		boolean Missiles; // HYD1
		boolean Rockets;
		boolean Guns;
		boolean Bombs;
		boolean Auto;
		boolean BLANK;
		boolean GCSTransf;
		boolean Avionics;
		double Stick;
		double Throttle;
		boolean Pressurization;
		boolean IFFOVR;
		boolean CB24_MainLPCocx;
		boolean CB24_HYD_Press;
		boolean CB24_CDU;
		boolean CB24_ASI;
		boolean CB24_HDR;
		boolean CB24_AC_Pitch;
		boolean CB24_LP_Pump_Port;
		boolean CB24_UC_Ctrl;
		boolean CB24_MSTR_ARMT;
		boolean CB24_GPS;
		boolean CB24_WarningLights;
		boolean CB24_ServoCtrl;
		boolean CB24_LP_Pump_STBD;
		boolean CB24_UC_Pos_Indicator;
		boolean CB24_SI;
		boolean CB24_Oxy1;
		boolean CB24_Oxy2;
		boolean CB24_EMG_HD_Pump;
		boolean CB24_UHF;
		boolean CB24_IFF;     
		boolean CB24_AH;      //Artificial Horizon
		boolean CB24_CAB_T;   //Cabin Temperature
		boolean CB24_START;
		boolean CB24_MBM;
		boolean CDU_Page_L1;
		boolean CDU_Page_L2;
		boolean CDU_Page_L3;
		boolean CDU_Page_L4;
		boolean CDU_Page_L5;
		boolean CDU_Page_R1;
		boolean CDU_Page_R2;
		boolean CDU_Page_R3;
		boolean CDU_Page_R4;
		boolean CDU_Page_R5;
		boolean CDU_Left_TST;
		boolean CDU_Left_PRV;
		boolean CDU_Left_NXT;
		boolean CDU_Left_BRT;
		boolean CDU_Left_DIM;
		boolean CDU_Numpad_N1;
		boolean CDU_Numpad_N2;
		boolean CDU_Numpad_N3;
		boolean CDU_Numpad_N4;
		boolean CDU_Numpad_N5;
		boolean CDU_Numpad_N6;
		boolean CDU_Numpad_N7;
		boolean CDU_Numpad_N8;
		boolean CDU_Numpad_N9;
		boolean CDU_Numpad_N_Ent;
		boolean CDU_Numpad_N0;
		boolean CDU_Numpad_N_CLR;
		boolean CDU_Right_ATK;
		boolean CDU_Right_AA;
		boolean CDU_Right_REC;
		boolean CDU_Right_NAV;
		boolean CDU_Right_DIV;
		boolean CDU_Right_MEN;
		boolean CDU_Right_OPS;
		boolean CDU_Right_EMG;
		boolean CDU_Right_GUID;
		boolean CDU_Right_FUEL;
		boolean CDU_Right_FIX;
		boolean CDU_Right_N12;
		boolean CDU_Right_ALT;
		boolean CDU_Right_IFF;
		boolean CDU_Right_DCL;
		boolean CDU_Right_N16;
		boolean UFP_Left_N1;
		boolean UFP_Left_ACK;
		boolean UFP_Left_MEN;
		boolean UFP_Left_NT;
		boolean UFP_Left_FW;
		boolean UFP_Left_SGL;
		boolean UFP_Left_NAV;
		boolean UFP_Left_TH;
		boolean UFP_Left_NXT;
		boolean UFP_Left_N10;
		boolean UFP_Left_CHR;
		boolean UFP_Left_IFF;
		boolean UFP_Numpad_N1;
		boolean UFP_Numpad_N2;
		boolean UFP_Numpad_N3;
		boolean UFP_Numpad_N4;
		boolean UFP_Numpad_N5;
		boolean UFP_Numpad_N6;
		boolean UFP_Numpad_N7;
		boolean UFP_Numpad_N8;
		boolean UFP_Numpad_N9;
		boolean UFP_Numpad_N_Ent;
		boolean UFP_Numpad_N0;
		boolean UFP_Numpad_N_CLR;
		boolean UFP_Right_DRF_CO;
		boolean UFP_Right_VEL;
		boolean UFP_Right_DCL;
		boolean NAU;
		boolean IFFON;
		boolean OverSpeed;
		boolean GauTst;
		boolean IncidTst;
		boolean CbyF;
		boolean FuelDump;
      		boolean UC_Down;
		boolean TankJet;
		boolean WinJet;
		boolean FuselageJet;
		boolean Prty;
		boolean REC;
		boolean UNK;
		boolean ABrk_Override;
		boolean MainLP;
		boolean LPPump1;
		boolean LPPump2;
		boolean AB_Left;
		boolean IGN_Ventil;
		boolean StartIGN;
   };
   #pragma keylist DaqData ID	  

};
