//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: DAQ_Data.cpp
//  Source: DAQ_Data.idl
//  Generated: Tue Dec 11 10:08:45 2012
//  OpenSplice V5.5.1OSS
//  
//******************************************************************

#include "DAQ_Data.h"




