//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: FDMData.cpp
//  Source: ../../../idl/FDMData.idl
//  Generated: Wed Oct 24 10:05:08 2012
//  OpenSplice V5.5.1OSS
//  
//******************************************************************

#include "FDMData.h"




