//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: FDMDataDcps.cpp
//  Source: bld/FDMDataDcps.idl
//  Generated: Wed Oct 24 10:05:08 2012
//  OpenSplice V5.5.1OSS
//  
//******************************************************************

#include "FDMDataDcps.h"

#if DDS_USE_EXPLICIT_TEMPLATES
template class DDS_DCPSUFLSeq < FDMData::Msg, struct MsgSeq_uniq_>;
#endif

const char * FDMData::MsgTypeSupportInterface::_local_id = "IDL:FDMData/MsgTypeSupportInterface:1.0";

FDMData::MsgTypeSupportInterface_ptr FDMData::MsgTypeSupportInterface::_duplicate (FDMData::MsgTypeSupportInterface_ptr p)
{
   if (p) p->m_count++;
   return p;
}

DDS::Boolean FDMData::MsgTypeSupportInterface::_local_is_a (const char * _id)
{
   if (strcmp (_id, FDMData::MsgTypeSupportInterface::_local_id) == 0)
   {
      return true;
   }

   typedef DDS::TypeSupport NestedBase_1;

   if (NestedBase_1::_local_is_a (_id))
   {
      return true;
   }

   return false;
}

FDMData::MsgTypeSupportInterface_ptr FDMData::MsgTypeSupportInterface::_narrow (DDS::Object_ptr p)
{
   FDMData::MsgTypeSupportInterface_ptr result = NULL;
   if (p && p->_is_a (FDMData::MsgTypeSupportInterface::_local_id))
   {
      result = dynamic_cast < FDMData::MsgTypeSupportInterface_ptr> (p);
      result->m_count++;
   }
   return result;
}

FDMData::MsgTypeSupportInterface_ptr FDMData::MsgTypeSupportInterface::_unchecked_narrow (DDS::Object_ptr p)
{
   FDMData::MsgTypeSupportInterface_ptr result;
   result = dynamic_cast < FDMData::MsgTypeSupportInterface_ptr> (p);
   result->m_count++;
   return result;
}

const char * FDMData::MsgDataWriter::_local_id = "IDL:FDMData/MsgDataWriter:1.0";

FDMData::MsgDataWriter_ptr FDMData::MsgDataWriter::_duplicate (FDMData::MsgDataWriter_ptr p)
{
   if (p) p->m_count++;
   return p;
}

DDS::Boolean FDMData::MsgDataWriter::_local_is_a (const char * _id)
{
   if (strcmp (_id, FDMData::MsgDataWriter::_local_id) == 0)
   {
      return true;
   }

   typedef DDS::DataWriter NestedBase_1;

   if (NestedBase_1::_local_is_a (_id))
   {
      return true;
   }

   return false;
}

FDMData::MsgDataWriter_ptr FDMData::MsgDataWriter::_narrow (DDS::Object_ptr p)
{
   FDMData::MsgDataWriter_ptr result = NULL;
   if (p && p->_is_a (FDMData::MsgDataWriter::_local_id))
   {
      result = dynamic_cast < FDMData::MsgDataWriter_ptr> (p);
      result->m_count++;
   }
   return result;
}

FDMData::MsgDataWriter_ptr FDMData::MsgDataWriter::_unchecked_narrow (DDS::Object_ptr p)
{
   FDMData::MsgDataWriter_ptr result;
   result = dynamic_cast < FDMData::MsgDataWriter_ptr> (p);
   result->m_count++;
   return result;
}

const char * FDMData::MsgDataReader::_local_id = "IDL:FDMData/MsgDataReader:1.0";

FDMData::MsgDataReader_ptr FDMData::MsgDataReader::_duplicate (FDMData::MsgDataReader_ptr p)
{
   if (p) p->m_count++;
   return p;
}

DDS::Boolean FDMData::MsgDataReader::_local_is_a (const char * _id)
{
   if (strcmp (_id, FDMData::MsgDataReader::_local_id) == 0)
   {
      return true;
   }

   typedef DDS::DataReader NestedBase_1;

   if (NestedBase_1::_local_is_a (_id))
   {
      return true;
   }

   return false;
}

FDMData::MsgDataReader_ptr FDMData::MsgDataReader::_narrow (DDS::Object_ptr p)
{
   FDMData::MsgDataReader_ptr result = NULL;
   if (p && p->_is_a (FDMData::MsgDataReader::_local_id))
   {
      result = dynamic_cast < FDMData::MsgDataReader_ptr> (p);
      result->m_count++;
   }
   return result;
}

FDMData::MsgDataReader_ptr FDMData::MsgDataReader::_unchecked_narrow (DDS::Object_ptr p)
{
   FDMData::MsgDataReader_ptr result;
   result = dynamic_cast < FDMData::MsgDataReader_ptr> (p);
   result->m_count++;
   return result;
}

const char * FDMData::MsgDataReaderView::_local_id = "IDL:FDMData/MsgDataReaderView:1.0";

FDMData::MsgDataReaderView_ptr FDMData::MsgDataReaderView::_duplicate (FDMData::MsgDataReaderView_ptr p)
{
   if (p) p->m_count++;
   return p;
}

DDS::Boolean FDMData::MsgDataReaderView::_local_is_a (const char * _id)
{
   if (strcmp (_id, FDMData::MsgDataReaderView::_local_id) == 0)
   {
      return true;
   }

   typedef DDS::DataReaderView NestedBase_1;

   if (NestedBase_1::_local_is_a (_id))
   {
      return true;
   }

   return false;
}

FDMData::MsgDataReaderView_ptr FDMData::MsgDataReaderView::_narrow (DDS::Object_ptr p)
{
   FDMData::MsgDataReaderView_ptr result = NULL;
   if (p && p->_is_a (FDMData::MsgDataReaderView::_local_id))
   {
      result = dynamic_cast < FDMData::MsgDataReaderView_ptr> (p);
      result->m_count++;
   }
   return result;
}

FDMData::MsgDataReaderView_ptr FDMData::MsgDataReaderView::_unchecked_narrow (DDS::Object_ptr p)
{
   FDMData::MsgDataReaderView_ptr result;
   result = dynamic_cast < FDMData::MsgDataReaderView_ptr> (p);
   result->m_count++;
   return result;
}



